name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
env:
  GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - run: pip install mkdocs mkdocs-material mkdocs-material-extensions pip install mkdocs-git-revision-date-localized-plugin mkdocs-glightbox mkdocs-macros-plugin mkdocs-video pillow cairosvg
      - name: deploy-pages
        run: mkdocs gh-deploy --force
      - name: deploy-offline
        env:
          OFFLINE: true
        run: mkdocs gh-deploy --force --remote-branch offline
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Offline Manual"