name: release
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.DEPLOY_KEY }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Offline Version"